name: Bug Report
description: Report a bug or incorrect mapping
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      options:
        - Incorrect mapping
        - UI/UX issue
        - Data error
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What's wrong?
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true
  
  - type: textarea
    id: evidence
    attributes:
      label: Evidence (if mapping issue)
      description: Links to official standard documentation
      placeholder: Paste links to standards documentation
  
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 120, Firefox 121, etc.
