name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New standard addition
        - UI/UX enhancement
        - API feature
        - Export capability
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve?
      placeholder: Why is this feature needed?
    validations:
      required: true
  
  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: How would you implement this? (optional)
      placeholder: Technical approach, mockups, examples
